// Auto-generated by Neon. Do not edit.

type FieldDescriptor = {
  type: "text";
  flags: TextOption[] | undefined | null;
  tokenizer: string | undefined | null;
  index: IndexRecordOption | undefined | null;
} | {
  type: "string";
  flags: TextOption[] | undefined | null;
} | {
  type: "f64";
  flags: NumericOption[] | undefined | null;
};
interface FuzzyTermQueryOptions {
  max_distance: number;
  transposition_costs_one: boolean;
  is_prefix: boolean;
}
interface IndexOptions {
  heapSize: number;
  reloadOn: ReloadOnPolicy;
}
type IndexRecordOption = "BASIC" | "WITH_FREQS" | "WITH_FREQS_AND_POSITIONS";
type LanguageName = "Arabic" | "Danish" | "Dutch" | "English" | "Finnish" | "French" | "German" | "Greek" | "Hungarian" | "Italian" | "Norwegian" | "Portuguese" | "Romanian" | "Russian" | "Spanish" | "Swedish" | "Tamil" | "Turkish";
type NumericOption = "STORED" | "INDEXED";
type ReloadOnPolicy = "COMMIT_WITH_DELAY" | "MANUAL";
interface SearchOptions {
  top: number;
}
interface TextAnalyzerFilters {
  removeLong: number | undefined | null;
  alphaNumOnly: boolean;
  asciiFolding: boolean;
  lowerCase: boolean;
  stemmer: LanguageName | undefined | null;
  filterStopWords: LanguageName | undefined | null;
}
type TextOption = "STORED";
interface Token {
  byteOffsetFrom: number;
  byteOffsetTo: number;
  charOffsetFrom: number;
  charOffsetTo: number;
  position: number;
  text: string;
  positionLength: number;
}

export declare class Index {
  constructor(path: string, schema: Schema, options: IndexOptions | undefined | null);
  commit(): Promise<undefined>;
  commitSync(): void;
  reload(): Promise<undefined>;
  reloadSync(): void;
  addDocument(document: any): any;
  searcher(): Searcher;
  registerTokenizer(name: string, tokenizer: TextAnalyzer): void;
}
export declare class Query {
  constructor(query: any);
}
export declare class Schema {
  constructor(fields: Record<string, FieldDescriptor>);
  fields(): Record<string, FieldDescriptor>;
}
export declare class Searcher {
  constructor(index: any);
  termQuery(term: string, field: string, options: IndexRecordOption | undefined | null): Query;
  phraseQuery(terms: string[], field: string): Query;
  fuzzyTermQuery(term: string, field: string, options: FuzzyTermQueryOptions | undefined | null): Query;
  regexpQuery(pattern: string, field: string): Query;
  phrasePrefixQuery(terms: string[], field: string): Query;
  searchSync(query: Query, options: SearchOptions | undefined | null): any;
  search(query: Query, options: SearchOptions | undefined | null): Promise<any>;
  searchTerms(field: string, pattern: string): string[];
}
export declare class TextAnalyzer {
  constructor(filters: TextAnalyzerFilters | undefined | null);
  tokenize(text: string): Token[];
}

export declare function generateTypescriptDeclarations(): string;
