declare module "./load.cjs" {
  // Auto-generated by Neon. Do not edit.

  export type FieldDescriptor = { "type": "text", flags: Array<TextOption> | null, tokenizer: string | null, index: IndexRecordOption | null, } | { "type": "string", flags: Array<TextOption> | null, } | { "type": "f64", flags: Array<NumericOption> | null, };
  export type FuzzyTermQueryOptions = { maxDistance: number, transpositionCostsOne: boolean, isPrefix: boolean, };
  export type IndexOptions = { heapSize: number, reloadOn: ReloadPolicy, };
  export type IndexRecordOption = "BASIC" | "WITH_FREQS" | "WITH_FREQS_AND_POSITIONS";
  export type Language = "Arabic" | "Danish" | "Dutch" | "English" | "Finnish" | "French" | "German" | "Greek" | "Hungarian" | "Italian" | "Norwegian" | "Portuguese" | "Romanian" | "Russian" | "Spanish" | "Swedish" | "Tamil" | "Turkish";
  export type NumericOption = "STORED" | "INDEXED";
  export type ReloadPolicy = "COMMIT_WITH_DELAY" | "MANUAL";
  export type SearchOptions = { top: number, };
  export type TextAnalyzerOptions = { removeLong: number | null, alphaNumOnly: boolean, asciiFolding: boolean, lowerCase: boolean, stemmer: Language | null, filterStopWords: Language | null, };
  export type TextOption = "STORED";
  export type Token = { byteOffsetFrom: number, byteOffsetTo: number, charOffsetFrom: number, charOffsetTo: number, position: number, text: string, positionLength: number, };

  export declare class Index {
    constructor(path: string, schema: Schema, options: IndexOptions | null);
    commit(): Promise<void>;
    commitSync(): void;
    reload(): Promise<void>;
    reloadSync(): void;
    addDocument(document: any): bigint;
    searcher(): Searcher;
    registerTokenizer(name: string, tokenizer: TextAnalyzer): void;
  }
  export declare class Query {
  }
  export declare class Schema {
    constructor(fields: { [key in string]: FieldDescriptor });
    fields(): { [key in string]: FieldDescriptor };
  }
  export declare class Searcher {
    termQuery(term: string, field: string, options: IndexRecordOption | null): Query;
    phraseQuery(terms: string[], field: string): Query;
    fuzzyTermQuery(term: string, field: string, options: FuzzyTermQueryOptions | null): Query;
    regexpQuery(pattern: string, field: string): Query;
    phrasePrefixQuery(terms: string[], field: string): Query;
    searchSync(query: Query, options: SearchOptions | null): [number, string][];
    search(query: Query, options: SearchOptions | null): Promise<[number, string][]>;
    searchTerms(field: string, pattern: string): string[];
  }
  export declare class TextAnalyzer {
    constructor(filters: TextAnalyzerOptions | null);
    tokenize(text: string): Token[];
  }

}

export {};
